# Generated by carnix 0.10.0: carnix generate-nix --standalone --src .
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# rustlings-4.1.0

    crates.rustlings."4.1.0" = deps: { features?(features_.rustlings."4.1.0" deps {}) }: buildRustCrate {
      crateName = "rustlings";
      version = "4.1.0";
      authors = [ "Marisa <mokou@posteo.de>" "Carol (Nichols || Goulding) <carol.nichols@gmail.com>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      crateBin =
        [{  name = "rustlings";  path = "src/main.rs"; }];
      dependencies = mapFeatures features ([
        (cratesIO.crates."clap"."${deps."rustlings"."4.1.0"."clap"}" deps)
        (cratesIO.crates."console"."${deps."rustlings"."4.1.0"."console"}" deps)
        (cratesIO.crates."indicatif"."${deps."rustlings"."4.1.0"."indicatif"}" deps)
        (cratesIO.crates."notify"."${deps."rustlings"."4.1.0"."notify"}" deps)
        (cratesIO.crates."regex"."${deps."rustlings"."4.1.0"."regex"}" deps)
        (cratesIO.crates."serde"."${deps."rustlings"."4.1.0"."serde"}" deps)
        (cratesIO.crates."toml"."${deps."rustlings"."4.1.0"."toml"}" deps)
      ]);
    };
    features_.rustlings."4.1.0" = deps: f: updateFeatures f (rec {
      clap."${deps.rustlings."4.1.0".clap}".default = true;
      console."${deps.rustlings."4.1.0".console}".default = true;
      indicatif."${deps.rustlings."4.1.0".indicatif}".default = true;
      notify."${deps.rustlings."4.1.0".notify}".default = true;
      regex."${deps.rustlings."4.1.0".regex}".default = true;
      rustlings."4.1.0".default = (f.rustlings."4.1.0".default or true);
      serde = fold recursiveUpdate {} [
        { "${deps.rustlings."4.1.0".serde}"."derive" = true; }
        { "${deps.rustlings."4.1.0".serde}".default = true; }
      ];
      toml."${deps.rustlings."4.1.0".toml}".default = true;
    }) [
      (cratesIO.features_.clap."${deps."rustlings"."4.1.0"."clap"}" deps)
      (cratesIO.features_.console."${deps."rustlings"."4.1.0"."console"}" deps)
      (cratesIO.features_.indicatif."${deps."rustlings"."4.1.0"."indicatif"}" deps)
      (cratesIO.features_.notify."${deps."rustlings"."4.1.0"."notify"}" deps)
      (cratesIO.features_.regex."${deps."rustlings"."4.1.0"."regex"}" deps)
      (cratesIO.features_.serde."${deps."rustlings"."4.1.0"."serde"}" deps)
      (cratesIO.features_.toml."${deps."rustlings"."4.1.0"."toml"}" deps)
    ];


# end

  };

  rustlings = crates.crates.rustlings."4.1.0" deps;
  __all = [ (rustlings {}) ];
  deps.aho_corasick."0.7.3" = {
    memchr = "2.2.0";
  };
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.8";
  };
  deps.assert_cmd."0.11.1" = {
    escargot = "0.4.0";
    predicates = "1.0.1";
    predicates_core = "1.0.0";
    predicates_tree = "1.0.0";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.2";
    libc = "0.2.58";
    winapi = "0.3.8";
  };
  deps.autocfg."0.1.4" = {};
  deps.bitflags."1.0.4" = {};
  deps.cfg_if."0.1.9" = {};
  deps.clap."2.33.0" = {
    atty = "0.2.11";
    bitflags = "1.0.4";
    strsim = "0.8.0";
    textwrap = "0.11.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.11.0";
  };
  deps.clicolors_control."1.0.0" = {
    lazy_static = "1.3.0";
    libc = "0.2.58";
    atty = "0.2.11";
    winapi = "0.3.8";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.4";
  };
  deps.console."0.7.7" = {
    atty = "0.2.11";
    clicolors_control = "1.0.0";
    lazy_static = "1.3.0";
    libc = "0.2.58";
    parking_lot = "0.8.0";
    regex = "1.1.6";
    unicode_width = "0.1.5";
    termios = "0.3.1";
    encode_unicode = "0.3.5";
    winapi = "0.3.8";
  };
  deps.console."0.8.0" = {
    clicolors_control = "1.0.0";
    lazy_static = "1.3.0";
    libc = "0.2.58";
    regex = "1.1.6";
    unicode_width = "0.1.5";
    termios = "0.3.1";
    encode_unicode = "0.3.5";
    winapi = "0.3.8";
  };
  deps.difference."2.0.0" = {};
  deps.encode_unicode."0.3.5" = {};
  deps.escargot."0.4.0" = {
    lazy_static = "1.3.0";
    log = "0.4.6";
    serde = "1.0.92";
    serde_json = "1.0.39";
  };
  deps.filetime."0.2.5" = {
    cfg_if = "0.1.9";
    redox_syscall = "0.1.54";
    libc = "0.2.58";
  };
  deps.float_cmp."0.4.0" = {
    num_traits = "0.2.8";
  };
  deps.fsevent."0.4.0" = {
    bitflags = "1.0.4";
    fsevent_sys = "2.0.1";
  };
  deps.fsevent_sys."2.0.1" = {
    libc = "0.2.58";
  };
  deps.fuchsia_cprng."0.1.1" = {};
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.0.4";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.glob."0.3.0" = {};
  deps.indicatif."0.10.3" = {
    console = "0.8.0";
    lazy_static = "1.3.0";
    number_prefix = "0.2.8";
    parking_lot = "0.8.0";
    regex = "1.1.6";
  };
  deps.inotify."0.7.0" = {
    bitflags = "1.0.4";
    inotify_sys = "0.1.3";
    libc = "0.2.58";
  };
  deps.inotify_sys."0.1.3" = {
    libc = "0.2.58";
  };
  deps.iovec."0.1.2" = {
    libc = "0.2.58";
    winapi = "0.2.8";
  };
  deps.itoa."0.4.4" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.3.0" = {};
  deps.lazycell."1.2.1" = {};
  deps.libc."0.2.58" = {};
  deps.lock_api."0.2.0" = {
    scopeguard = "1.0.0";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.9";
  };
  deps.memchr."2.2.0" = {};
  deps.mio."0.6.19" = {
    iovec = "0.1.2";
    log = "0.4.6";
    net2 = "0.2.33";
    slab = "0.4.2";
    fuchsia_zircon = "0.3.3";
    fuchsia_zircon_sys = "0.3.3";
    libc = "0.2.58";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.mio_extras."2.0.5" = {
    lazycell = "1.2.1";
    log = "0.4.6";
    mio = "0.6.19";
    slab = "0.4.2";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.33";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.net2."0.2.33" = {
    cfg_if = "0.1.9";
    libc = "0.2.58";
    winapi = "0.3.8";
  };
  deps.normalize_line_endings."0.2.2" = {};
  deps.notify."4.0.15" = {
    bitflags = "1.0.4";
    filetime = "0.2.5";
    libc = "0.2.58";
    walkdir = "2.2.7";
    inotify = "0.7.0";
    mio = "0.6.19";
    mio_extras = "2.0.5";
    fsevent = "0.4.0";
    fsevent_sys = "2.0.1";
    winapi = "0.3.8";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.4";
  };
  deps.number_prefix."0.2.8" = {
    num_traits = "0.2.8";
  };
  deps.numtoa."0.1.0" = {};
  deps.parking_lot."0.8.0" = {
    lock_api = "0.2.0";
    parking_lot_core = "0.5.0";
    rustc_version = "0.2.3";
  };
  deps.parking_lot_core."0.5.0" = {
    cfg_if = "0.1.9";
    rand = "0.6.5";
    smallvec = "0.6.9";
    rustc_version = "0.2.3";
    cloudabi = "0.0.3";
    redox_syscall = "0.1.54";
    libc = "0.2.58";
    winapi = "0.3.8";
  };
  deps.predicates."1.0.1" = {
    difference = "2.0.0";
    float_cmp = "0.4.0";
    normalize_line_endings = "0.2.2";
    predicates_core = "1.0.0";
    regex = "1.1.6";
  };
  deps.predicates_core."1.0.0" = {};
  deps.predicates_tree."1.0.0" = {
    predicates_core = "1.0.0";
    treeline = "0.1.0";
  };
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.quote."0.6.12" = {
    proc_macro2 = "0.4.30";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.4";
    libc = "0.2.58";
    winapi = "0.3.8";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.4";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.58";
    winapi = "0.3.8";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.58";
    winapi = "0.3.8";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.4";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.54" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.54";
  };
  deps.regex."1.1.6" = {
    aho_corasick = "0.7.3";
    memchr = "2.2.0";
    regex_syntax = "0.6.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.6.6" = {
    ucd_util = "0.1.3";
  };
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.rustlings."4.1.0" = {
    clap = "2.33.0";
    console = "0.7.7";
    indicatif = "0.10.3";
    notify = "4.0.15";
    regex = "1.1.6";
    serde = "1.0.92";
    toml = "0.4.10";
  };
  deps.ryu."0.2.8" = {};
  deps.same_file."1.0.4" = {
    winapi_util = "0.1.2";
  };
  deps.scopeguard."1.0.0" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.92" = {
    serde_derive = "1.0.92";
  };
  deps.serde_derive."1.0.92" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.34";
  };
  deps.serde_json."1.0.39" = {
    itoa = "0.4.4";
    ryu = "0.2.8";
    serde = "1.0.92";
  };
  deps.slab."0.4.2" = {};
  deps.smallvec."0.6.9" = {};
  deps.strsim."0.8.0" = {};
  deps.syn."0.15.34" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    unicode_xid = "0.1.0";
  };
  deps.termion."1.5.2" = {
    numtoa = "0.1.0";
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    redox_termios = "0.1.1";
  };
  deps.termios."0.3.1" = {
    libc = "0.2.58";
  };
  deps.textwrap."0.11.0" = {
    unicode_width = "0.1.5";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.toml."0.4.10" = {
    serde = "1.0.92";
  };
  deps.treeline."0.1.0" = {};
  deps.ucd_util."0.1.3" = {};
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.utf8_ranges."1.0.2" = {};
  deps.vec_map."0.8.1" = {};
  deps.walkdir."2.2.7" = {
    same_file = "1.0.4";
    winapi = "0.3.8";
    winapi_util = "0.1.2";
  };
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.8" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_util."0.1.2" = {
    winapi = "0.3.8";
  };
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
}
